name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  IMAGE_NAME: kacg-cicd-app

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
          cache: gradle

      # Gradle wrapper 실행 권한 부여
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      # Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test --no-daemon

      # Docker 빌드
      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .

      # AWS 자격 증명 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # AWS ECR 로그인
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Docker 태그
      - name: Tag Docker image
        run: |
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ secrets.ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/${{ env.IMAGE_NAME }}:latest

      # Docker Push
      - name: Push to ECR
        run: |
          docker push ${{ secrets.ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/${{ env.IMAGE_NAME }}:latest

      # EC2 접속 후 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # AWS CLI 설정 (EC2에서 ECR 접근을 위해)
            aws configure set region ap-northeast-2
            
            # ECR 로그인
            aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ secrets.ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com

            # 기존 컨테이너 중지 및 삭제
            docker stop ${{ env.IMAGE_NAME }} || true
            docker rm ${{ env.IMAGE_NAME }} || true

            # 최신 이미지 pull
            docker pull ${{ secrets.ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/${{ env.IMAGE_NAME }}:latest

            # 환경변수 설정
            export JWT_SECRET_KEY=$(aws ssm get-parameter --name "/kacg-cicd/jwt-secret" --with-decryption --query "Parameter.Value" --output text)
            export DB_NAME=$(aws ssm get-parameter --name "/kacg-cicd/db/dbname" --query "Parameter.Value" --output text)
            export DB_USER=$(aws ssm get-parameter --name "/kacg-cicd/db/username" --query "Parameter.Value" --output text)
            export DB_PASS=$(aws ssm get-parameter --name "/kacg-cicd/db/password" --with-decryption --query "Parameter.Value" --output text)
            export DB_HOST=$(aws ssm get-parameter --name "/kacg-cicd/db/endpoint" --query "Parameter.Value" --output text)
            export DB_PORT=$(aws ssm get-parameter --name "/kacg-cicd/db/port" --query "Parameter.Value" --output text)
            export DB_URL="jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&useSSL=false"

            # 컨테이너 실행
            docker run -d \
              --name ${{ env.IMAGE_NAME }} \
              -p 8080:8080 \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e SPRING_CONFIG_IMPORT="" \
              -e JWT_SECRET_KEY=$JWT_SECRET_KEY \
              -e DB_URL=$DB_URL \
              -e DB_USERNAME=$DB_USER \
              -e DB_PASSWORD=$DB_PASS \
              ${{ secrets.ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/${{ env.IMAGE_NAME }}:latest
